CREATE TABLE IF NOT EXISTS VENTATICKETS (
    ID INTEGER PRIMARY KEY,  -- ID es la clave primaria
    FOLIO INTEGER NOT NULL,
    CAJA_ID INTEGER NOT NULL,
    CAJERO_ID INTEGER NOT NULL,
    NOMBRE TEXT NOT NULL,
    CREADO_EN TEXT NOT NULL,  -- Formato de fecha y hora YYYY-MM-DD HH:MM:SS
    SUBTOTAL REAL,
    IMPUESTOS REAL,
    TOTAL REAL NOT NULL,
    GANANCIA REAL,
    ESTA_ABIERTO INTEGER,  -- Booleano (1 para true, 0 para false)
    CLIENTE_ID INTEGER,
    VENDIDO_EN TEXT,  -- Formato de fecha y hora YYYY-MM-DD HH:MM:SS
    ES_MODIFICABLE TEXT,  -- Booleano (t para true, f para false)
    PAGO_CON REAL,
    MONEDA TEXT,
    NUMERO_ARTICULOS INTEGER,
    PAGADO_EN TEXT,  -- Formato de fecha y hora YYYY-MM-DD HH:MM:SS
    ESTA_CANCELADO TEXT,  -- Booleano (t para true, f para false))
    OPERACION_ID INTEGER,
    OLD_TICKET_ID INTEGER,
    NOTAS BLOB,
    IMPRIMIR_NOTA TEXT,  -- Booleano (t para true, f para false))
    FORMA_PAGO TEXT,
    REFERENCIA TEXT,
    FACTURA_ID INTEGER,
    TOTAL_DEVUELTO REAL
);



CREATE TABLE IF NOT EXISTS VENTATICKETS_ARTICULOS (
    ID INTEGER PRIMARY KEY,  -- ID es la clave primaria
    TICKET_ID INTEGER NOT NULL,
    PRODUCTO_CODIGO VARCHAR(50) NOT NULL,
    PRODUCTO_NOMBRE TEXT NOT NULL,
    CANTIDAD REAL NOT NULL,
    GANANCIA REAL,
    DEPARTAMENTO_ID INTEGER,
    PAGADO_EN TEXT NOT NULL,  -- Formato de fecha y hora YYYY-MM-DD HH:MM:SS
    USA_MAYOREO TEXT,  -- Booleano (t para true, f para false))
    PORCENTAJE_DESCUENTO REAL,
    COMPONENTES TEXT,
    IMPUESTOS_USADOS TEXT,
    IMPUESTO_UNITARIO REAL,
    PRECIO_USADO REAL,
    CANTIDAD_DEVUELTA REAL,
    FUE_DEVUELTO TEXT,  -- Booleano (t para true, f para false))
    PORCENTAJE_PAGADO REAL
);

CREATE TABLE IF NOT EXISTS PRODUCTOS (
    CODIGO VARCHAR(50) PRIMARY KEY,
    DESCRIPCION TEXT NOT NULL,
    TVENTA TEXT NOT NULL,
    PCOSTO REAL,
    PVENTA REAL NOT NULL,
    DEPT INTEGER,
    MAYOREO REAL,
    IPRIORIDAD INTEGER,
    DINVENTARIO REAL,
    DINVMINIMO REAL,
    DINVMAXIMO REAL,
    CHECADO_EN TEXT,
    PORCENTAJE_GANANCIA INTEGER
);


